"""指标模式定义"""

INDICATOR_PATTERNS = {
    'ma': {'category': '量价类', 'type': '趋势', 'name': '均线', 'window': True},
    'ma_dev': {'category': '量价类', 'type': '趋势', 'name': '均线偏离度', 'window': True},
    'high_new': {'category': '量价类', 'type': '趋势', 'name': '是否新高', 'window': True},
    'low_new': {'category': '量价类', 'type': '趋势', 'name': '是否新低', 'window': True},
    'mom': {'category': '量价类', 'type': '动量', 'name': '动量', 'window': True},
    'return_acf1': {'category': '量价类', 'type': '动量', 'name': '趋势连续度', 'window': True},
    'erp': {'category': '量价类', 'type': '动量', 'name': '股债风险溢价', 'window': False},
    'margin': {'category': '量价类', 'type': '情绪', 'name': '两融余额', 'window': False},
    'north': {'category': '量价类', 'type': '情绪', 'name': '北向资金', 'window': False},
    'net_subscription': {'category': '量价类', 'type': '情绪', 'name': '净申购', 'window': False},
    'annualized_basis': {'category': '量价类', 'type': '情绪', 'name': '年化基差', 'window': False},
    'iv': {'category': '量价类', 'type': '动量', 'name': '隐含波动率', 'window': False},
    'vol': {'category': '量价类', 'type': '动量', 'name': '波动率', 'window': True},
    'amt': {'category': '量价类', 'type': '情绪', 'name': '成交额', 'window': False},
    'pchg_abs': {'category': '量价类', 'type': '情绪', 'name': '涨跌幅绝对值', 'window': False},
    'rs': {'category': '量价类', 'type': '情绪', 'name': '相对强弱', 'window': False},
    'rt': {'category': '量价类', 'type': '情绪', 'name': '相对换手率', 'window': False},
    'rsi': {'category': '量价类', 'type': '动量', 'name': 'RSI', 'window': True},
    'pe_ttm': {'category': '估值类', 'type': '估值', 'name': '市盈率TTM', 'window': False},
    'pb_lf': {'category': '估值类', 'type': '估值', 'name': '市净率LF', 'window': False},
    'ps_ttm': {'category': '估值类', 'type': '估值', 'name': '市销率TTM', 'window': False},
    'val_pcf_ocfttmwgt': {'category': '估值类', 'type': '估值', 'name': '市现率OCF_TTM加权', 'window': False},
    'val_dividendyield3': {'category': '估值类', 'type': '估值', 'name': '股息率3年', 'window': False},
    'roe_ttm2': {'category': '估值类', 'type': '估值', 'name': 'ROE_TTM2', 'window': False},
    'yoy_or': {'category': '估值类', 'type': '估值', 'name': '营收同比', 'window': False},
    'debttoassets': {'category': '估值类', 'type': '估值', 'name': '资产负债率', 'window': False},
}
